### ISSUE TITLE
Overlay is preventing scrollbar from functioning for large dialogs

### ISSUE THREAD

**Issue by bgse** [likeastore/ngDialog#94]
When opening a large dialog (one that would require the user to scroll in order to see all content), the overflow scrollbar is located "behind" the opaque overlay, and on most browsers cannot be interacted with.

See this screenshot, note the "greyed-out" scrollbar on the right:

![scrollbar_issue](https://cloud.githubusercontent.com/assets/8385202/4542321/81978ef4-4e20-11e4-81d9-1337ab33e0bf.png)

Firefox:
- when dialog is open, scrollbar appears to be "behind" the overlay, you cannot interact with the scrollbar, trying to do so will immediately trigger dialog close.

Chrome:
- scrollbar is not visually behind the overlay, but the interaction issue is the same as with firefox.

Safari:
- exact same problem as chrome, no direct visual effect, but no interaction

InternetExplorer11:
- scrollbar is visually behind the overlay, but interaction does work as expected, you can in fact use the scrollbar.

**Comment by TheProdigyFilippo** [comment]
Hi. This bug is closed, but it looks like it still exists. Checked on the 6680647684d43c288c0327247baf0f0278603dc1 commit. It would be nice to have this functionality working.

**Comment by TheProdigyFilippo** [comment]
Scolling when mouse pointer is on modal content works, but there is still an issue with scrolling when mouse pointer is on overlay. I tried to workaround with solution found in #63 suggested by lagr - adding ngdialog-overlay to className and set overlay to false:
```javascript
className: 'your-custom-classes ngdialog-overlay',
overlay: false,
```
It works partially, because for example in Chrome, some content shows even after few seconds (non-deterministic - sometimes rapidly, sometimes not). Content is there, but it is not visible. So I added another z-index to .ngdialog-content:
```css
.ngdialog-content {
  z-index: 10001;
}
```
to my CSS theme and it looks like problem is resolved for now. Content loads normally. But it is only workaround. Sorry that I can't give you proper sollution, but I'm not good in JS, CSS.

Cheers

**Comment by darrenshrwd** [comment]
I just took latest code and still have this issue also, it makes the dialog unusable for large content, dialog content will scroll with a mouse wheel, but of course most people use laptops.

**Comment by thbsolutions** [comment]
Still wondering why this isn't fixed yet, also have this issue :(

**Comment by egor-smirnov** [comment]
@TheProdigyFilippo @thbsolutions @daanoz if you want this fixed ASAP, please submit the PR. I am currently a bit busy to do it right now.

**Comment by leitasat** [comment]
The possible solution is changing 
```css
.ngdialog-overlay{
...
  right: 0;
...
}
```
to 
```css
.ngdialog-overlay{
...
  right: 15px;
...
}
```
but one needs to get the number '15' from a browser because the width probably depends on it. Could not come up with such a script immediately.

**Comment by faceleg** [comment]
Is this still an issue?

**Comment by darrenshrwd** [comment]
Although there are suggestions above I don't think anyone has committed a fix?...my product is still several months away so I don't have motivation to look into fixing myself (or failing that switch to another lib) yet.

**Comment by faceleg** [comment]
Thanks for replying.

If motivation strikes, know that we are waiting.

**Comment by leitasat** [comment]
@faceleg yes it is. My hack does not work properly if a popup does not need a scroll bar (transparent strip occurs)

**Comment by agungsb** [comment]
I faced the same problem but I managed to solve the problem by change this (from file ngDialog.js):

```javascript
$dialog.html((options.overlay ?
                                '<div class="ngdialog-overlay"></div><div class="ngdialog-content" role="document">' + template + '</div>' :
                                '<div class="ngdialog-content" role="document">' + template + '</div>'));
```

to:

```javascript
$dialog.html((options.overlay ?
                                '<div class="ngdialog-overlay"><div class="ngdialog-content" role="document">' + template + '</div>' :
                                '<div class="ngdialog-content" role="document">' + template + '</div></div>'));
```

I moved ngdialog-content to be the children of ngdialog-overlay. I haven't found any problem so far, but seriously, is there any reason why ngdialog-content is not the children of ngdialog-overlay at the first place?

**Comment by faceleg** [comment]
Would you submit a pr so we can get a focused review of this change going? I'd like to see his issue resolved.

**Comment by agungsb** [comment]
@faceleg I'm sorry, I'm new to Github. So I need plenty of time to submit a PR, but I already have submitted it.

**Comment by MiguelMike** [comment]
I actually think that the best option would be to either:
a) scale the dialog to fit the available real estate and enable scrolling of it's content
b) not use the dialog if its content is too large to fit within the viewport

I'd go for option A

**Comment by faceleg** [comment]
@agungsb did your PR resolve this issue?

@MiguelMike I agree that A sounds good, PR?

**Comment by MiguelMike** [comment]
@faceleg Sorry, no PR for this one. I'm using flexbox layout for dialog. This could be not something everyone would choose. [Here's a nice guide to flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

Here's some basic styling for `.dialog` and `.ngdialog-content`. Deeper elements should be styled according to indivitual needs.

 **NOTE:** Remove prefixes if you don't need cross-browser compatibility.

```css
.dialog {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1000;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-align-items: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
}

.ngdialog-content {
    position: relative;
    z-index: 1000;
    background: #fff;
    -webkit-flex: 0 0 auto;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    -webkit-flex-flow: column;
    -ms-flex-flow: column;
    flex-flow: column;
    width: 100%;
    max-height: 80%;
    overflow: hidden;
    padding: 0;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    max-width: 70%;
    border-radius: 0;
```

**Comment by haikyuu** [comment]
Here is a little hack if you just need the scroll-bar to work:
```css
.ngdialog-overlay .ngdialog-overlay {
    display: none;
}
```
The overlay color is now lighter but you can change it in the same way

**Comment by jpatel3** [comment]
Any plan to include this change officially, instead of css hacks or temp solutions?

**Comment by MiguelMike** [comment]
That overlay prevents from scrolling is perfectly correct. To change this behavior you can use any of the "hacks" mentioned in previous comments. That said, I don't think that there can be a simple solution to satisfy all users.

There could be multiple additional classes to fix the scrolling issue for different situations, but I still think that the basic functionality is just fine and if doesn't work for you it can be fixed by simply adding your own CSS.

**Comment by faceleg** [comment]
We're not adding anything unless it works for at least 99% of all users, and doesn't break current installs.

Basically, what @MiguelMike said.

**Comment by faceleg** [comment]
I'm closing this, if one of the above suggestions doesn't work feel free to comment with one that does.

**Comment by jpatel3** [comment]
Not sure if I would agree with comment that it works for 99% of all users. Here are the two cases -

- If you don't have trackpad or scroll on mouse, it doesn't work in Firefox (Where scrollbar is behind the overlay)
- In chrome it shows the scrollbar, but its not draggable.

With said that, I have also take suggestion from above and applied the temp fix with css. 

I was just suggesting, that instead of using the css from this issue thread, it should be part of the lib itself, otherwise scrollbar should not appear all together (if its there/visible it should be working.)

**Comment by darrenshrwd** [comment]
I guess I'll try the hiakyuu fix when I need to, but I have to say I totally agree with above comment and fail to see any reason at all why issue should be closed, would have thought most web dialogs allow content scroll like bootstrap modal does. Just because nobody has the time or inclination to fix it (myself included) does not stop it being a valid issue.

**Comment by faceleg** [comment]
If someone would like to contribute a fix that doesn't break other functionality, that'd be great!

**Comment by darrenshrwd** [comment]
Hi I tried the @agungsb fix and that did not solve the issue for me and also broke the scrollwheell, I tried the @hiakyuu fix and that did not work for me either.

Sorry to not contribute a fix, however for those needing a lightweight dialog I found the following that works for my requirements:

https://github.com/LukaszWatroba/v-modal

Note that it is using flexbox to center the dialog, but in IE9 it just sits off to the left and is still functional.

**Comment by CasherWest** [comment]
Another solution is to add this:
```
.ngdialog-overlay .ngdialog-overlay {
    pointer-events: none;
}
```

**Comment by azadnio** [comment]
yes,
```javascript
.ngdialog-overlay {
    pointer-events: none;
}
```
works

**Comment by MiguelMike** [comment]
Not sure what this solves, but there's one important problem it introduces. It breaks the `closeByDocument` functionality.

I think that having a dialog higher than available viewport doesn't make any sense. Such dialogs indicate that a website is poorly built. Try making the dialog small enough to fit on screen and allow the content within to scroll.

**Comment by saracen7** [comment]
This should really bee flagged as a known issue on the home page, before anyone invests the time and effort before they realise the problem.

Anyway, here is a possible fix I had to implement. It works for me, but I dont use any of the animation so I'm not sure if it breaks any of that.
1. Added a container around ng-dialog-content (called ngdialog-container) - line 496
2. Changed the css so that ngdialog overflow is visible
3. Added css for ngdialog-container:    
    width: 100%;
    height: 100%;
    overflow-y: scroll;
    position: relative;
4. In order to keep the closebydocument functionalty I changed the closeByDocumentHandler function to target the new container rather than the overlay

Hope it works for you guys

**Comment by faceleg** [comment]
@saracen7 we'd really love it if you could update the readme so it mentions this, a PR?

You could add a "known issue" section that is a list of known issues, with links to a wiki page for each known issue.

**Comment by saracen7** [comment]
Im a github novice so I have done as you asked but have no idea if thats whats required

**Comment by ppaann** [comment]
Here is how I solve it:

// use the ngdialog as overlay (which has already the position, top...setup)
.ngdialog{
background-color: rgba(0, 0, 0, 0.5);
}
// the overlay is actually useless
.ngdialog .ngdialog-overlay {
    display: none;
}
// then give some size to the dialog content and put it in the middle
.ngdialog .ngdialog-content {
    position: relative;
    margin: 5% auto;
    width: 80%;
    min-width: 450px;
}

**Comment by sandeep-rajbhandari** [comment]
.ngdialog-overlay {
    pointer-events: none;
}
works for me too

**Comment by jherencia** [comment]
This breaks closeByDocument option:

`.ngdialog-overlay {
pointer-events: none;
}`

But this does not, and keeps the animation ngdialog-overlay has:
`.ngdialog {
  -webkit-animation: ngdialog-fadein 0.5s;
  animation: ngdialog-fadein 0.5s;
  background: rgba(0, 0, 0, .4);
  &.ngdialog-closing {
    -webkit-animation: ngdialog-fadeout 0.5s;
    animation: ngdialog-fadeout 0.5s;
  }
}

.ngdialog-overlay {
  display: none;
}`

**Comment by faceleg** [comment]
It seems people have found a good solution for this. If someone wants to submit a PR with a non-breaking fix, feel free.

Locking thread.
